name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Clonez le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurez l'accès SSH à l'EC2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Construisez votre application
      - name: Build application
        run: |
          npm install
          npm run build

      # Autorise l'action github
      - name: Add host to known_hosts
        run: ssh-keyscan -H <YOUR_EC2_PUBLIC_IP> >> ~/.ssh/known_hosts

      # Déployez les fichiers sur l'instance EC2
      - name: Deploy to EC2
        run: |
          scp -r ./dist/* ubuntu@${{ secrets.APP_EC2_IP }}:${{ secrets.APP_EC2_PATH }}
          ssh ubuntu@${{ secrets.APP_EC2_IP }} 'sudo systemctl restart nginx'
