name: Quality

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js avec cache npm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Installer les dépendances avec npm ci
      - run: npm ci

      # Linting du code
      - name: Run ESLint
        run: npm run lint
        
      # Exécuter les tests
      - name: Run Tests
        run: npm test 

